### ISSUE TITLE
Dropbox too small

### ISSUE THREAD

**Issue by jerrywoo96** [AkaXiiaoBii/mdoujin_v2_public_updates#10]
I'm not using desktop mode, and this is my viewport. I can't see the contents in the dropbox.

![Screenshot_2023-06-07-04-07-42-786_com android chrome](https://github.com/AkaXiiaoBii/mdoujin_v2_public_updates/assets/26324139/a63bfa3c-5bd6-42cb-aefb-2fb84d7d4829)
![1686081974357](https://github.com/AkaXiiaoBii/mdoujin_v2_public_updates/assets/26324139/25a8daab-af45-4ab1-93de-ab98fbdc46a8)
![1686081974449](https://github.com/AkaXiiaoBii/mdoujin_v2_public_updates/assets/26324139/8c1f5e39-beb0-4909-bb7c-5001a759ad7f)
![1686081974530](https://github.com/AkaXiiaoBii/mdoujin_v2_public_updates/assets/26324139/9d18d2ec-f446-49e8-aa15-4adc8d5928e8)
![1686081974612](https://github.com/AkaXiiaoBii/mdoujin_v2_public_updates/assets/26324139/d33036cd-b551-458b-b5cb-86e4a45da9b3)
![1686081974692](https://github.com/AkaXiiaoBii/mdoujin_v2_public_updates/assets/26324139/3de9cb48-55e6-42ac-b0c4-82c3cf1ae089)

**Comment by AkaXiiaoBii** [comment]
Hi @jerrywoo96 , may I know what mobile devices/tablets are you using?  

I have acknowledged this bug due to the resolution issue, and will fix it at a later time

**Comment by jerrywoo96** [comment]
Redmi Note 10 Pro (Global)
M2101K6G

**Comment by KuroShion** [comment]
> Redmi Note 10 Pro (Global) M2101K6G

Shouldn't be an issue by default but because you had changed your screen size then it will cause issue.
The issue will caused when your screen viewport is more than 600px as browser will think is a larger device and automatically provide a tablet/pc mode browser type

**Comment by jerrywoo96** [comment]
In javascript, there is this property `navigator.userAgent`. Which returns the User-Agent of the browser. Maybe you can check for the keyword `Mobile` if its a mobile platform and adjust accordingly?

**Comment by AkaXiiaoBii** [comment]
![image](https://github.com/AkaXiiaoBii/mdoujin_v2_public_updates/assets/29534833/6a27f389-59f6-4384-8f2d-7b4f7956365d)
Bug fixed and updated to production recently

**Comment by jerrywoo96** [comment]
Works great!
