### ISSUE TITLE
Bug: Invalid Google Maps Embed API Key

### ISSUE THREAD

**Issue by jerrywoo96** [AkaXiiaoBii/mdoujin_v2_public_updates#2]
![image](https://user-images.githubusercontent.com/26324139/230760083-aaf163e6-a64a-4932-88dc-1d6312c0ad36.png)

Your google maps embed api key is invalid. Actually, you do not need to use any api key for the google maps embed api service. you can use this code without any api key instead.

`<iframe src="https://maps.google.com/maps?output=embed&q=City%20Square%20Mall%20Johor"></iframe>`

**Comment by AkaXiiaoBii** [comment]
![image](https://user-images.githubusercontent.com/29534833/230763750-fc3d4765-f74a-4768-a1f3-51f294d2af66.png)
Hi jerrywoo96, thank you for the bug reporting with the solution, your solution helps me for resolve issue quickly, I had updated my code to MDoujin live production.
