### ISSUE TITLE
Suggestion: Proper Issue/Suggestion Template

### ISSUE THREAD

**Issue by EggY0lk** [AkaXiiaoBii/mdoujin_v2_public_updates#3]
Adding a template for issues/suggestions should enable easier troubleshooting and feature suggestions.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by AkaXiiaoBii** [comment]
Hi EggY0lk, thank you for sharing this and the guidelines, I will improve the template for letting everyone more convenience! 
Will inform you here if any updates/progress.

**Comment by AkaXiiaoBii** [comment]
Hi EggY0lk, I did set up a simple issue/suggestion template, FYI, I will utilize this Github platform like the Discussions board for any future project updates. 

Thanks for your suggestion!

**Comment by EggY0lk** [comment]
Thanks a lot for all the work on the website as well!
