### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by EggY0lk** [AkaXiiaoBii/mdoujin_v2_public_updates#5]
**Is your feature request related to a problem? Please describe.**
My eyes sometimes get tired from viewing the website as I need to plan for the many anime conventions happening on consecutive weekends.

**Describe the solution you'd like**
An eye-friendly dark mode option.

**Describe alternatives you've considered**
My current alternative solution is to use a third-party browser extension called [dark reader](https://darkreader.org/) but it is not perfect as some elements are not displayed correctly.

**Additional context**
![image](https://user-images.githubusercontent.com/27946481/236404299-2f1e9c19-a94d-46b6-94f3-a0bbb5e911d6.png)
This is what the website looks like using the dark reader extension on the default settings. Some of the words are hard to be read.

**Comment by AkaXiiaoBii** [comment]
Thanks for your suggestion, at the moment I will not be planning to implement this for the current version, but I will take it into consideration for the next major UI update ya

**Comment by EggY0lk** [comment]
Alright, thanks! Looking forward to it.
