### ISSUE TITLE
Ongoing event not shown when show active events only is checked.

### ISSUE THREAD

**Issue by jerrywoo96** [AkaXiiaoBii/mdoujin_v2_public_updates#6]
When the event is still ongoing like running for 2 days, event is not shown when show active events is checked.

For eg,
Event runs from sat to sun.
On sunday, when filter is checked, the event list does not show the still ongoing event that is still active.

What I'm guessing is that your show active event filter is comparing against today and the event start date, such that the event is already considered past when today is later than start date.

Would it make more sense if it was checked against the event end date instead to be considered as past event?

Thanks!

**Comment by AkaXiiaoBii** [comment]
Thanks for the bug report, will get back to you when the bug was fixed.

**Comment by AkaXiiaoBii** [comment]
Issue fixed, example test scenario:

![image](https://github.com/AkaXiiaoBii/mdoujin_v2_public_updates/assets/29534833/4d1cd053-0d15-4d21-a5cf-e0389b67b225)

**Comment by jerrywoo96** [comment]
I'll test again this weekend, and will help close this issue if no problems.
