### ISSUE TITLE
Event List showing side by side

### ISSUE THREAD

**Issue by jerrywoo96** [AkaXiiaoBii/mdoujin_v2_public_updates#8]
![image](https://github.com/AkaXiiaoBii/mdoujin_v2_public_updates/assets/26324139/1ef661e1-5977-46ba-9ddd-563833e0ecd9)

Previously it was much nicer and more intuitive to see the list of events. But the layout has changed to side by side.
This is my viewport.

![image](https://github.com/AkaXiiaoBii/mdoujin_v2_public_updates/assets/26324139/4e83ff1c-b088-47cd-aa83-0984f43f67c6)

**Comment by jerrywoo96** [comment]
Also, would it be possible to show a dropdown for the user to select how many events to show per page?

**Comment by AkaXiiaoBii** [comment]
Hi [jerrywoo96](https://github.com/jerrywoo96), Thank you for your bug report.

For recent changes last week, I just changed the UI part from single-row lists to two-rows and it only applies to resolution 800px above. Mobile will be kept as a single row as well.

To understand your bug inquiry, do you mean "Side by Side" is referred to the current event list had becomes to 2-rows?

**Comment by AkaXiiaoBii** [comment]
> Also, would it be possible to show a dropdown for the user to select how many events to show per page?

I will mark it down for new UI enhancements and also will show how many records were filled out and the page numbers too.

And if the effort was not too much, I will be adding the dropdown field (events per page) as well.

Once again, thanks for your feedback.

**Comment by jerrywoo96** [comment]
Side by side meaning 2 columns. Based on UX, a list is supposed to be read vertically down, while columns are supposed to be data related to other data in the same row like excel. Currently i find it not intuitive to read from left to right, as it is not how we normally read lists. Unless the items have thumbnails, like youtube, shopee or lazada, then it is perfectly fine to have columns.

**Comment by jerrywoo96** [comment]
I think changing of ui layout such as the display of list into 2 columns should be surveyed in the fb group, to see if users are ok with the ui change that may affect UX.

**Comment by AkaXiiaoBii** [comment]
Yup,  I am agreed that your view, especially regarding the UX principles, and I will decide on reverting to the last changes at a later time.

Btw, the next UI major update will be supporting the upload picture part, so every event will have the thumbnail parts as you mention.

Once again, thanks for the valuable sharing of information!

**Comment by AkaXiiaoBii** [comment]
I had reverted to the previous version recently, for your information, thank you.
